name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: ghcr.io/manetu/ci-tools:3.1
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: ghaskins/docker-multistage-action@dev
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        image: ${{ github.repository }}
        stages: foo,bar
        tags: v1.0,v1.0.0
        platforms: linux/amd64,linux/arm64

#    - name: Generate artifact attestation
#      uses: actions/attest-build-provenance@v2
#      with:
#        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
#        subject-digest: ${{ steps.push.outputs.digest }}
#        push-to-registry: true
